#!/bin/sh
base_path=/srv/rnaseq-app
app_path=$base_path/rnaseq-web-app
backend=$app_path/backend

python_env="/srv/py-venvs/current"
cd $backend
sh $python_env/bin/activate
export PYTHONPATH=$base_path/GWASModules/:$app_path/:$base_path/GWASModules/variation/src/

$python_env/bin/python __init__.py

